---
- name: Setup n8n on EC2 Ubuntu com .env e swap
  hosts: all
  become: yes

  tasks:

    # === SWAP CONFIGURATION ===
    - name: Criar arquivo de swap (2GB)
      command: fallocate -l 2G /swapfile
      args:
        creates: /swapfile

    - name: Definir permissões corretas para o swap
      file:
        path: /swapfile
        owner: root
        group: root
        mode: '0600'

    - name: Criar sistema de swap
      command: mkswap /swapfile
      when: ansible_swaptotal_mb == 0

    - name: Ativar swap
      command: swapon /swapfile
      when: ansible_swaptotal_mb == 0

    - name: Adicionar swap ao fstab
      mount:
        name: swap
        src: /swapfile
        fstype: swap
        opts: sw
        state: present

    - name: Ajustar swappiness
      sysctl:
        name: vm.swappiness
        value: 10
        state: present
        sysctl_set: yes
        reload: yes

    # === NODEJS CONFIGURATION ===

    - name: Aguardar liberação do dpkg lock
      shell: |
        while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "Aguardando liberação do dpkg lock..."
          sleep 3
        done
      args:
        executable: /bin/bash

    - name: Adicionar repositório Node.js 20.x (NodeSource)
      shell: curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
      args:
        executable: /bin/bash

    - name: Instalar Node.js 20.x e npm
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Verificar versão do Node.js
      command: node -v
      register: node_version

    - name: Verificar versão do npm
      command: npm -v
      register: npm_version

    - name: Instalar PM2 globalmente
      npm:
        name: pm2
        global: yes

    - name: Instalar n8n globalmente
      npm:
        name: n8n
        global: yes

    - name: Copiar arquivo .env para o servidor
      copy:
        src: ./files/.env
        dest: /home/ubuntu/.env
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Exportar variáveis do .env no bashrc
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'export $(grep -v "^#" /home/ubuntu/.env | xargs)'
        insertafter: EOF
